const tokens = [
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron1ndu2wvkrxtane8se2tr48gv7nsm46y5gcqjhux/MARS',
    symbol: 'MARS',
    icon: '/images/MARS.svg',
    description: 'Mars Token',
    protocolIconLight: '/images/MARS.svg',
    protocolIconDark: '/images/MARS.svg',
    decimals: 6,
    isLST: false,
    protocol: 'Cosmos Hub',
    brandColor: '#2E3148',
  },
  {
    chainId: 'neutron-1',
    denom: 'untrn',
    symbol: 'NTRN',
    icon: '/images/NTRN.svg',
    description: 'Neutron Token',
    protocolIconLight: '/images/NTRN.svg',
    protocolIconDark: '/images/NTRN.svg',
    decimals: 6,
    isLST: false,
    protocol: 'Neutron',
    brandColor: '#3B82F6',
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/B559A80D62249C8AA07A380E2A2BEA6E5CA9A6F079C912C3A9E9B494105E4F81',
    symbol: 'USDC',
    icon: '/images/USDC.svg',
    description: 'USD Coin',
    protocolIconLight: '/images/USDC.svg',
    protocolIconDark: '/images/USDC.svg',
    decimals: 6,
    isLST: false,
    protocol: 'Circle',
    brandColor: '#2775CA',
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/B7BF60BB54433071B49D586F54BD4DED5E20BEFBBA91958E87488A761115106B',
    symbol: 'LBTC',
    icon: '/images/LBTC.svg',
    description: 'Lombard Bitcoin',
    protocolIconLight: '/images/lombard/lombardIconOnly.svg',
    protocolIconDark: '/images/lombard/lombardIconOnlyDark.svg',
    decimals: 8,
    isLST: true,
    protocol: 'Lombard Finance',
    brandColor: '#22C55E', // Lombard green (vibrant green)
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/C0F284F165E6152F6DDDA900537C1BC8DA1EA00F03B9C9EC1841FA7E004EF7A3',
    symbol: 'solvBTC',
    icon: '/images/solvBTC.svg',
    description: 'Solv Bitcoin',
    protocolIconLight: '/images/solv/solvLight.png',
    protocolIconDark: '/images/solv/solvDark.png',
    decimals: 18,
    isLST: true,
    protocol: 'Solv Protocol',
    brandColor: '#EAB308', // Solv yellow
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/E2A000FD3EDD91C9429B473995CE2C7C555BCC8CFC1D0A3D02F514392B7A80E8',
    symbol: 'eBTC',
    icon: '/images/eBTC.png',
    description: 'Edge Bitcoin',
    protocolIconLight: '/images/eBTC.png',
    protocolIconDark: '/images/eBTC.png',
    decimals: 8,
    isLST: true,
    protocol: 'Edge Protocol',
    brandColor: '#EC4899', // Edge pink
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/1075520501498E008B02FD414CD8079C0A2BAF9657278F8FB8F7D37A857ED668',
    symbol: 'pumpBTC',
    icon: '/images/pumpBTC.svg',
    description: 'Pump Bitcoin',
    protocolIconLight: '/images/pump.svg',
    protocolIconDark: '/images/pump.svg',
    decimals: 8,
    isLST: true,
    protocol: 'Pump Protocol',
    brandColor: '#3B82F6', // Pump blue
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/3F1D988D9EEA19EB0F3950B4C19664218031D8BCE68CE7DE30F187D5ACEA0463',
    symbol: 'uniBTC',
    icon: '/images/uniBTC.svg',
    description: 'Bedrock Bitcoin',
    protocolIconLight: '/images/bedrock.svg',
    protocolIconDark: '/images/bedrock.svg',
    decimals: 8,
    isLST: true,
    protocol: 'Bedrock',
    brandColor: '#A855F7', // Bedrock purple (slightly different from Solv)
  },
  {
    chainId: 'neutron-1',
    denom: 'ibc/0E293A7622DC9A6439DB60E6D234B5AF446962E27CA3AB44D0590603DFF6968E',
    symbol: 'wBTC',
    icon: '/images/WBTC.svg',
    description: 'Wrapped Bitcoin (Eureka)',
    protocolIconLight: '/images/eureka/eurekaLight.svg',
    protocolIconDark: '/images/eureka/eurekaDark.svg',
    decimals: 8,
    isLST: true,
    protocol: 'Eureka',
    brandColor: '#F97316', // Eureka orange (classic Bitcoin orange)
  },
]
export default tokens
